/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Principal;

import javax.swing.JFrame;

/**
 *
 * @author Alex
 */
public class VentanaInicio extends javax.swing.JPanel {

    /**
     * Creates new form VentanaPrinc
     */
    VentanaPrinc padre;
    public VentanaInicio() {
        initComponents();
    }
    public VentanaInicio(VentanaPrinc frame) {
        initComponents();
        padre=frame;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Titulo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 25, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
