/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clientes;

import Citas.CitasForm;
import Facturacion.FacturacionForm;
import Mascotas.MascotaFicha;
import Mascotas.MascotasTabla;
import Principal.VentanaPrinc;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import Database.Database;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import java.util.List;
/**
 *
 * @author Alex
 */
public class ClientesForm extends javax.swing.JPanel {

    /**
     * Creates new form ClientesForm
     */
    private List<QueryDocumentSnapshot> documents;
    private long codigo=0;
    VentanaPrinc padre;
    
    
    public ClientesForm(VentanaPrinc frame,boolean editable) {
        initComponents();
        jTextField5.setText(String.valueOf(conseguirCodigo()));
        if(!editable){
            initModify(editable);
        }
        padre = frame;
    }
    public ClientesForm(VentanaPrinc frame,boolean editable,Object[] fila) {
        initComponents();
        jTextField5.setText(String.valueOf(conseguirCodigo()));
        if(!editable){
            initModify(editable);
            jTextField1.setText((String) fila[0]);
            jTextField2.setText((String) fila[1]);
            jTextField3.setText((String) fila[5]);
            jTextField4.setText((String) fila[2]);
            jTextField5.setText( String.valueOf(fila[4]));
            jTextField6.setText((String) fila[3]);
        }
        padre = frame;
    }
    public void habilitarEdicion(Boolean editable){
        jTextField1.setEditable(editable);
        jTextField2.setEditable(editable);
        jTextField3.setEditable(editable);
        jTextField4.setEditable(editable);
        jTextField6.setEditable(editable);        
    }
    public void initModify(boolean editable){
        habilitarEdicion(editable);
        jButton4.setText("Modificar");
    }
    public long conseguirCodigo() {
        documents = Database.accederDB("Clientes");
        if (!documents.isEmpty()) {
            codigo=documents.size();
            return (codigo);
        }
        return (0);
    }
    public ClientesForm(Boolean editable) {
        initComponents();
        jTextField5.setText(String.valueOf(conseguirCodigo()));
        
    }
    public void anadirCliente(Boolean add) {

        String nombre = jTextField1.getText();
        String Apellido = jTextField2.getText();
        String Telefono = jTextField3.getText();
        String E_mail = jTextField6.getText();
        String DNI = jTextField4.getText();
        Map<String, Object> data = new HashMap<>();
        data.put("Nombre", nombre);
        data.put("Apellidos", Apellido);
        data.put("Telefono", Telefono);
        if (add) {
            long Codigo = conseguirCodigo() + 1;
            data.put("Codigo", Codigo);
        }
        data.put("E-mail", E_mail);
        data.put("DNI", DNI);
        Database.insertarDatos("Clientes", DNI, data);
        jTextField5.setText(String.valueOf(conseguirCodigo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 29, -1, -1));

        jLabel2.setText("Apellido");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 61, -1, -1));

        jLabel3.setText("Telefono");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setText("E-mail");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel5.setText("Codigo Cliente");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel6.setText("DNI");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jTextField1.setText("Juan");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jTextField2.setText("Torcio");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jTextField3.setText("616161616");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jTextField4.setText("12346578f");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.setText("1");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jTextField6.setText("jt@gmail");
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel7.setText("Mascota");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jButton1.setText("Acceso Mascota");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jButton2.setText("Citar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jButton3.setText("Facturar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jButton4.setText("Añadir");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jButton5.setText("Eliminar");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jButton6.setText("Volver");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        padre.showMascotasFicha();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        padre.showCitasForm();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        padre.showFacturacionForm();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if (jButton4.getText().equals("Modificar")) {
            jButton4.setText("Confirmar");
            habilitarEdicion(true);
            jTextField4.setEditable(false);
        } else {
            if (jButton4.getText().equals("Confirmar")) {
                anadirCliente(false);
            } else {
                anadirCliente(true);
            }
        }

    }//GEN-LAST:event_jButton4MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        padre.showClientesTabla();
    }//GEN-LAST:event_jButton6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
