/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package Mascotas;

import Clientes.ClientesForm;
import Database.Database;
import Principal.VentanaPrinc;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;

/**
 *
 * @author Alex
 */
public class MascotaFicha extends javax.swing.JPanel {

    /** Creates new form MascotaFicha */
    VentanaPrinc padre;
    public MascotaFicha() {
        initComponents();
    }
    public MascotaFicha(VentanaPrinc frame) {
        initComponents();
        padre=frame;            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Caracter = new javax.swing.ButtonGroup();
        Sexo = new javax.swing.ButtonGroup();
        Esterilizacion = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jLabel2.setText("Edad");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 20));

        jLabel3.setText("Especie");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, 20));

        jLabel4.setText("Raza");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 40, 20));

        jLabel5.setText("Codigo");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 40, 20));

        jLabel6.setText("Chip");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 40, 20));

        jTextField1.setText("jTextField1");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jTextField2.setText("jTextField2");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jTextField3.setText("jTextField3");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jTextField4.setText("jTextField4");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jTextField5.setText("jTextField5");
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jTextField6.setText("jTextField6");
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jButton1.setText("Historial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jButton2.setText("Informes");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jLabel7.setText("Caracter");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel8.setText("Sexo");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel9.setText("Esterilizacion");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        Caracter.add(jRadioButton1);
        jRadioButton1.setText("Tranquilo");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        Caracter.add(jRadioButton2);
        jRadioButton2.setText("Agresivo");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        Caracter.add(jRadioButton3);
        jRadioButton3.setText("Nervioso");
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        Sexo.add(jRadioButton4);
        jRadioButton4.setText("Macho");
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        Sexo.add(jRadioButton5);
        jRadioButton5.setText("Hembra");
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        Esterilizacion.add(jRadioButton6);
        jRadioButton6.setText("Si");
        add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        Esterilizacion.add(jRadioButton7);
        jRadioButton7.setText("No");
        add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jButton3.setText("Acceder Cliente");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jButton4.setText("Modificar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jButton5.setText("Eliminar");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jLabel10.setText("Cliente");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jTextField7.setText("jTextField7");
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        //padre.showClientesFormNoEditable();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String nombre = jTextField1.getText();
        String edad = jTextField2.getText();
        String especie = jTextField3.getText();
        String Codigo = jTextField5.getText();
        String Chip = jTextField6.getText();
        String raza = jTextField4.getText();
        Map<String, Object> data = new HashMap<>();
        String caracter;
        
        
        data.put("Nombre", nombre);
        data.put("edad", edad);
        data.put("especie", especie);
        data.put("Chip", Chip);
        data.put("Codigo", Codigo);
        data.put("raza", raza);        
        
        Database.insertarDatos("Clientes", Codigo, data);
    }//GEN-LAST:event_jButton4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Caracter;
    private javax.swing.ButtonGroup Esterilizacion;
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
